const products = [
    {
        "id": "asd",
        "category": "backpack",
        "flag": "Новинка",
        "sale": false,
        "name": "Городской рюкзак “Signature”",
        "oldprice": 2990,
        "newprice": 2390,
        "img": "../img/promo__item--01.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/avatar.png","../img/photo.png","../img/avatar.png","../img/photo.png","../img/photo.png" ],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": 2,
        "category": "backpack",
        "flag": "Новинка",
        "sale": false,
        "name": "Городской рюкзак “Signature”",
        "oldprice": 2990,
        "newprice": 2390,
        "img": "../img/promo__item--01.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/photo.png","../img/avatar.png","../img/photo.png","../img/photo.png","../img/photo.png" ],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": 3,
        "category": "backpack",
        "flag": "Старинк",
        "sale": false,
        "name": "Городской рюкзак “Signature”",
        "oldprice": 2990,
        "newprice": 2390,
        "img": "../img/promo__item--01.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/photo.png","../img/photo.png","../img/photo.png","../img/photo.png","../img/avatar.png" ],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": 4,
        "category": "backpack",
        "flag": "Новинка",
        "sale": false,
        "name": "Городской рюкзак “Signature”",
        "oldprice": 2990,
        "newprice": 2390,
        "img": "../img/promo__item--01.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/photo.png","../img/avatar.png","../img/photo.png","../img/photo.png","../img/photo.png" ],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": 5,
        "category": "backpack",
        "flag": "-20%",
        "sale": true,
        "name": "Городской рюкзак “Signature”",
        "oldprice": 2990,
        "newprice": 2390,
        "img": "../img/promo__item--01.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/photo.png","../img/photo.png","../img/avatar.png","../img/photo.png","../img/photo.png" ],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": 6,
        "category": "backpack",
        "flag": "Новинка",
        "sale": false,
        "name": "Городской рюкзак “Signature”",
        "oldprice": 2990,
        "newprice": 2390,
        "img": "../img/promo__item--01.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/photo.png","../img/avatar.png","../img/photo.png","../img/photo.png","../img/photo.png" ],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": 7,
        "category": "backpack",
        "flag": "Новинка",
        "sale": false,
        "name": "Городской рюкзак “Signature”",
        "oldprice": 2990,
        "newprice": 2390,
        "img": "../img/promo__item--01.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/photo.png","../img/photo.png","../img/photo.png","../img/photo.png","../img/photo.png" ],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": 8,
        "category": "bags",
        "flag": "Новинка",
        "sale": false,
        "name": "Сумка “Signature”",
        "oldprice": 5990,
        "newprice": 2390,
        "img": "../img/promo__item--01.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/photo.png","../img/photo.png","../img/photo.png","../img/avatar.png","../img/photo.png" ],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": 9,
        "category": "bags",
        "flag": "Старинк",
        "sale": false,
        "name": "Сумка “Signature”",
        "oldprice": 2990,
        "newprice": 2390,
        "img": "../img/promo__item--01.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/photo.png","../img/avatar.png","../img/photo.png","../img/photo.png","../img/photo.png" ],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": 10,
        "category": "bags",
        "flag": "-50%",
        "sale": true,
        "name": "Сумка “Signature”",
        "oldprice": 5990,
        "newprice": 2390,
        "img": "../img/promo__item--01.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/photo.png","../img/photo.png","../img/photo.png","../img/photo.png","../img/avatar.png" ],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": 11,
        "category": "purse",
        "flag": "Новинка",
        "sale": false,
        "name": "кошелек “Signature”",
        "oldprice": 2990,
        "newprice": 2390,
        "img": "../img/avatar.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/avatar.png","../img/photo.png","../img/photo.png","../img/photo.png","../img/photo.png" ],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": 12,
        "category": "purse",
        "flag": "-1%",
        "sale": true,
        "name": "Кошелек “Signature”",
        "oldprice": 12990,
        "newprice": 2390,
        "img": "../img/promo__item--02.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/photo.png","../img/photo.png","../img/avatar.png","../img/photo.png","../img/photo.png" ],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": 13,
        "category": "purse",
        "flag": "Новинка",
        "sale": false,
        "name": "кошелек “Signature”",
        "oldprice": 990,
        "newprice": 390,
        "img": "../img/promo__img.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/avatar.png","../img/photo.png","../img/photo.png","../img/photo.png","../img/photo.png" ],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": 14,
        "category": "purse",
        "flag": "Новинка",
        "sale": false,
        "name": "кошелек “Signature”",
        "oldprice": 90,
        "newprice": 39,
        "img": "../img/avatar.png",
        "size": "35x20x43",
        "description": "Внутренний карман на молнии",
        "pictures": ["../img/photo.png","../img/photo.png","../img/photo.png","../img/avatar.png","../img/photo.png" ],
        "material": "Полиуретан/Нейлон",
    }
]

