const products = [
    {
        "id": "cityBP1",
        "category": "backpack",
        "flag": "Новинка",
        "sale": false,
        "name": "Городской рюкзак №1",
        "oldprice": 2100,
        "newprice": 1690,
        "img": "../img/products/cityBP1/productCard.jpg",
        "size": "34x25x13.5",
        "description": "Три вместительных кармана один из них на молнии. Регулируемые стяжки. Три вида рисунка.",
        "pictures": ["../img/products/cityBP1/Group 320.png","../img/products/cityBP1/Group 319.png","../img/products/cityBP1/Group 321.png","../img/products/cityBP1/Group 322.png","../img/products/cityBP1/Group 323.png","../img/products/cityBP1/Group 324.png", "../img/products/cityBP1/Group 325.png", "../img/products/cityBP1/Group 327.png" ],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": "cityBP2",
        "category": "backpack",
        "flag": "Новинка",
        "sale": false,
        "name": "Городской рюкзак №2",
        "oldprice": 2100,
        "newprice": 1690,
        "img": "../img/products/cityBP2/productCard.jpg",
        "size": "34x25x13.5",
        "description": "Три вместительных кармана один из них на молнии. Регулируемые стяжки. Три вида рисунка.",
        "pictures": ["../img/products/cityBP2/Group 319.png","../img/products/cityBP2/Group 320.png","../img/products/cityBP2/Group 323.png","../img/products/cityBP2/Group 324.png","../img/products/cityBP2/Group 325.png" ],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": "cityBP3",
        "category": "backpack",
        "flag": "Новинка",
        "sale": false,
        "name": "Городской рюкзак №3",
        "oldprice": 2100,
        "newprice": 1690,
        "img": "../img/products/cityBP3/productCard.png",
        "size": "34x25x13.5",
        "description": "Три вместительных кармана один из них на молнии. Регулируемые стяжки. Три вида рисунка.",
        "pictures": ["../img/products/cityBP3/Group 319.png","../img/products/cityBP3/Group 320.png","../img/products/cityBP3/Group 323.png","../img/products/cityBP3/Group 324.png"],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": "bag-oneshoulder1",
        "category": "bags",
        "flag": "Новинка",
        "sale": false,
        "name": "Сумка на одно плечо-рюкзак №1",
        "oldprice": 2450,
        "newprice": 1650,
        "img": "../img/products/bag-oneshoulder1/productCard.jpg",
        "size": "18x6x31",
        "description": "Четыре наружных кармана два из них на молнии Два основных больших отделения, карман на молнии",
        "pictures": ["../img/products/bag-oneshoulder1/Group 320.png", "../img/products/bag-oneshoulder1/Group 330.png", "../img/products/bag-oneshoulder1/Group 331.png", "../img/products/bag-oneshoulder1/Rectangle 169.png", "../img/products/bag-oneshoulder1/Rectangle 170.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "bag-oneshoulder2",
        "category": "bags",
        "flag": "Новинка",
        "sale": false,
        "name": "Сумка на одно плечо-рюкзак №2",
        "oldprice": 2450,
        "newprice": 1650,
        "img": "../img/products/bag-oneshoulder2/productCard.png",
        "size": "18x6x31",
        "description": "Четыре наружных кармана два из них на молнии Два основных больших отделения, карман на молнии",
        "pictures": ["../img/products/bag-oneshoulder2/Group 320.png", "../img/products/bag-oneshoulder2/Rectangle 169.png", "../img/products/bag-oneshoulder2/Rectangle 169-1.png", "../img/products/bag-oneshoulder2/Rectangle 170.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "bag-oneshoulder3",
        "category": "bags",
        "flag": "Новинка",
        "sale": false,
        "name": "Сумка на одно плечо-рюкзак №3",
        "oldprice": 2450,
        "newprice": 1650,
        "img": "../img/products/bag-oneshoulder3/productCard.png",
        "size": "18x6x31",
        "description": "Четыре наружных кармана два из них на молнии Два основных больших отделения, карман на молнии",
        "pictures": ["../img/products/bag-oneshoulder3/Group 320.png", "../img/products/bag-oneshoulder3/Rectangle 169.png", "../img/products/bag-oneshoulder3/Rectangle 169-1.png", "../img/products/bag-oneshoulder3/Rectangle 170.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "porte-monnaie1",
        "category": "purse",
        "flag": "",
        "sale": false,
        "name": "Портмоне №1",
        "oldprice": 1790,
        "newprice": 890,
        "img": "../img/products/porte-monnaie1/productCard.jpg",
        "size": "20x10x3",
        "description": "Два основных отделения, множество кормашков под карточки-визитки, карман под молнией для мелочи.",
        "pictures": ["../img/products/porte-monnaie1/Rectangle 169.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "porte-monnaie2",
        "category": "purse",
        "flag": "",
        "sale": false,
        "name": "Портмоне №2",
        "oldprice": 1790,
        "newprice": 890,
        "img": "../img/products/porte-monnaie2/productCard.jpg",
        "size": "20x10x3",
        "description": "Два основных отделения, множество кормашков под карточки-визитки, карман под молнией для мелочи.",
        "pictures": ["../img/products/porte-monnaie2/Group 331.png", "../img/products/porte-monnaie2/Rectangle 169.png", "../img/products/porte-monnaie2/Rectangle 169-1.png", "../img/products/porte-monnaie2/Rectangle 169-2.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "purse1",
        "category": "purse",
        "flag": "",
        "sale": false,
        "name": "Кошлёк №1",
        "oldprice": 1200,
        "newprice": 690,
        "img": "../img/products/purse1/productCard.png",
        "size": "20x10x2.5",
        "description": "Три основных отделения, множество отделений под карточки-визитки, карман под молнией для мелочи.",
        "pictures": ["../img/products/purse1/Group 331.png", "../img/products/purse1/Group 335.png", "../img/products/purse1/Group 336.png", "../img/products/purse1/Group 337.png", "../img/products/purse1/Rectangle 169.png", "../img/products/purse1/Rectangle 169-1.png", "../img/products/purse1/Rectangle 169-2.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "BPmini1",
        "category": "backpack",
        "flag": "",
        "sale": false,
        "name": "Рюкзак mini №1",
        "oldprice": 2900,
        "newprice": 2100,
        "img": "../img/products/BPmini1/productCard.png",
        "size": "24*12*29",
        "description": "Три наружных кармана один из них на молнии. Одно основное большое отделение, три внутренних кармана, одно из них на молнии. Регулируемые лямки. Три вида рисунка.",
        "pictures": ["../img/products/BPmini1/Group 319.png","../img/products/BPmini1/Group 320.png","../img/products/BPmini1/Group 324.png","../img/products/BPmini1/Rectangle 169.png","../img/products/BPmini1/Rectangle 169-1.png", "../img/products/BPmini1/Rectangle 170.png" ],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": "BPmini2",
        "category": "backpack",
        "flag": "",
        "sale": true,
        "name": "Рюкзак mini №2",
        "oldprice": 2900,
        "newprice": 2100,
        "img": "../img/products/BPmini2/productCard.png",
        "size": "24*12*29",
        "description": "Три наружных кармана один из них на молнии. Одно основное большое отделение, три внутренних кармана, одно из них на молнии. Регулируемые лямки. Три вида рисунка.",
        "pictures": ["../img/products/BPmini2/Group 319.png","../img/products/BPmini2/Group 320.png","../img/products/BPmini2/Group 326.png"],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": "BPmini3",
        "category": "backpack",
        "flag": "",
        "sale": false,
        "name": "Рюкзак mini №3",
        "oldprice": 2900,
        "newprice": 2100,
        "img": "../img/products/BPmini3/productCard.png",
        "size": "24*12*29",
        "description": "Три наружных кармана один из них на молнии. Одно основное большое отделение, три внутренних кармана, одно из них на молнии. Регулируемые лямки. Три вида рисунка.",
        "pictures": ["../img/products/BPmini3/Group 320.png","../img/products/BPmini3/Group 327.png","../img/products/BPmini3/Group 328.png","../img/products/BPmini3/Rectangle 169.png","../img/products/BPmini3/Rectangle 170.png"],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": "BPbig1",
        "category": "backpack",
        "flag": "Новинка",
        "sale": false,
        "name": "Рюкзак большой №1",
        "oldprice": 3500,
        "newprice": 2450,
        "img": "../img/products/BPbig1/productCard.png",
        "size": "32*24*14",
        "description": "Ортопедическая спинка и лямки. Два основных больших отделения, два карман один из них на молнии. Регулируемые лямки. Три вида рисунка.",
        "pictures": ["../img/products/BPbig1/Group 327.png", "../img/products/BPbig1/Group 328.png","../img/products/BPbig1/Group 330.png","../img/products/BPbig1/Group 331.png","../img/products/BPbig1/Rectangle 169.png", "../img/products/BPbig1/Rectangle 170.png", "../img/products/BPbig1/Group 400.jpg"],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": "BPbig2",
        "category": "backpack",
        "flag": "",
        "sale": false,
        "name": "Рюкзак большой №2",
        "oldprice": 3600,
        "newprice": 2550,
        "img": "../img/products/BPbig2/productCard.png",
        "size": "36*26*15",
        "description": "Три наружных кармана один из них на молнии. Одно основное большое отделение, три внутренних кармана, одно из них на молнии",
        "pictures": ["../img/products/BPbig2/Group 327.png","../img/products/BPbig2/Rectangle 169.png", "../img/products/BPbig2/Rectangle 170.png", "../img/products/BPbig2/Rectangle 171.png", "../img/products/BPbig2/Rectangle 172.png", "../img/products/BPbig2/Rectangle 173.png", "../img/products/BPbig2/Rectangle 174.png"],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": "BPbig3",
        "category": "backpack",
        "flag": "",
        "sale": false,
        "name": "Рюкзак большой №3",
        "oldprice": 3600,
        "newprice": 2550,
        "img": "../img/products/BPbig3/productCard.jpg",
        "size": "36*26*15",
        "description": "Три наружных кармана один из них на молнии. Одно основное большое отделение, три внутренних кармана, одно из них на молнии",
        "pictures": ["../img/products/BPbig3/Group 320.png", "../img/products/BPbig3/Group 330.png", "../img/products/BPbig3/Rectangle 169.png", "../img/products/BPbig3/Rectangle 169-1.png", "../img/products/BPbig3/Rectangle 170.png", "../img/products/BPbig3/Rectangle 171.png", "../img/products/BPbig3/Rectangle 172.png"],
        "material": "Полиуретан/Нейлон"
    },
    {
        "id": "bag-banana1",
        "category": "bags",
        "flag": "Новинка",
        "sale": false,
        "name": "Сумка на пояс-бананка №1",
        "oldprice": 2690,
        "newprice": 1690,
        "img": "../img/products/bag-banana1/productCard.png",
        "size": "39*11*15",
        "description": "Одно основное большое отделение, один внутренний карман на молнии. Регулируемый ремень 80-110см (рисунок - ромб). Регулируемый ремень 86-113см (рисунок - цветок). Два вида рисунка.",
        "pictures": ["../img/products/bag-banana1/Group 330.png", "../img/products/bag-banana1/Group 331.png", "../img/products/bag-banana1/Rectangle 169.png", "../img/products/bag-banana1/Rectangle 170.png", "../img/products/bag-banana1/Rectangle 171.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "bag-banana2",
        "category": "bags",
        "flag": "Новинка",
        "sale": false,
        "name": "Сумка на пояс-бананка №2",
        "oldprice": 2690,
        "newprice": 1690,
        "img": "../img/products/bag-banana2/productCard.png",
        "size": "39*11*15",
        "description": "Одно основное большое отделение, один внутренний карман на молнии. Регулируемый ремень 80-110см (рисунок - ромб). Регулируемый ремень 86-113см (рисунок - цветок). Два вида рисунка.",
        "pictures": ["../img/products/bag-banana2/bag-banana2-1.jpg", "../img/products/bag-banana2/bag-banana2.jpg", "../img/products/bag-banana2/Group 331.png", "../img/products/bag-banana2/Rectangle 169.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "bagsmall1",
        "category": "bags",
        "flag": "",
        "sale": false,
        "name": "Сумка small №1",
        "oldprice": 2500,
        "newprice": 1590,
        "img": "../img/products/bagsmall1/productCard.png",
        "size": "28*18*13",
        "description": "Одно основное большое отделение, три внутренних кармана, одно из них на молнии. Лямка на плечо. Регулируемые лямки. Три вида рисунка.",
        "pictures": ["../img/products/bagsmall1/Group 330.png","../img/products/bagsmall1/Group 331.png", "../img/products/bagsmall1/Group 332.png","../img/products/bagsmall1/Group 333.png","../img/products/bagsmall1/Rectangle 170.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "bagsmall2",
        "category": "bags",
        "flag": "",
        "sale": false,
        "name": "Сумка small №2",
        "oldprice": 2500,
        "newprice": 1590,
        "img": "../img/products/bagsmall2/productCard.png",
        "size": "28*18*13",
        "description": "Одно основное большое отделение, три внутренних кармана, одно из них на молнии. Лямка на плечо. Регулируемые лямки. Три вида рисунка.",
        "pictures": ["../img/products/bagsmall2/Group 331.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "bagsmall3",
        "category": "bags",
        "flag": "",
        "sale": false,
        "name": "Сумка small №3",
        "oldprice": 2500,
        "newprice": 1590,
        "img": "../img/products/bagsmall3/productCard.png",
        "size": "28*18*13",
        "description": "Одно основное большое отделение, три внутренних кармана, одно из них на молнии. Лямка на плечо. Регулируемые лямки. Три вида рисунка.",
        "pictures": ["../img/products/bagsmall3/Group 327.png", "../img/products/bagsmall3/Group 331.png", "../img/products/bagsmall3/productCard.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "bagbig1",
        "category": "bags",
        "flag": "",
        "sale": false,
        "name": "Сумка big №1",
        "oldprice": 2800,
        "newprice": 1890,
        "img": "../img/products/bagbig1/productCard.png",
        "size": "38*26*13",
        "description": "Одно основное большое отделение, три внутренних кармана, одно из них на молнии. Лямка на плечо. Регулируемые лямки. Три вида рисунка.",
        "pictures": ["../img/products/bagbig1/Group 331.png", "../img/products/bagbig1/Group 332.png", "../img/products/bagbig1/Group 334.png", "../img/products/bagbig1/Group 336.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "bagbig2",
        "category": "bags",
        "flag": "",
        "sale": false,
        "name": "Сумка big №2",
        "oldprice": 2800,
        "newprice": 1890,
        "img": "../img/products/bagbig2/productCard.png",
        "size": "38*26*13",
        "description": "Одно основное большое отделение, три внутренних кармана, одно из них на молнии. Лямка на плечо. Регулируемые лямки. Три вида рисунка.",
        "pictures": ["../img/products/bagbig2/Group 331.png", "../img/products/bagbig2/Group 332.png", "../img/products/bagbig2/Rectangle 169.png", "../img/products/bagbig2/Rectangle 169-1.png", "../img/products/bagbig2/Rectangle 170.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "bagbig3",
        "category": "bags",
        "flag": "",
        "sale": false,
        "name": "Сумка big №3",
        "oldprice": 2800,
        "newprice": 1890,
        "img": "../img/products/bagbig3/productCard.jpg",
        "size": "38*26*13",
        "description": "Одно основное большое отделение, три внутренних кармана, одно из них на молнии. Лямка на плечо. Регулируемые лямки. Три вида рисунка.",
        "pictures": ["../img/products/bagbig3/Group 331.png", "../img/products/bagbig3/Group 332.png", "../img/products/bagbig3/Rectangle 169.png", "../img/products/bagbig3/Rectangle 169-1.png", "../img/products/bagbig3/Rectangle 170.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "bag-clutch",
        "category": "bags",
        "flag": "Новинка",
        "sale": false,
        "name": "Сумка-клатч",
        "oldprice": 2290,
        "newprice": 1690,
        "img": "../img/products/bag-clutch/productCard.png",
        "size": "28*18*7",
        "description": "Одно основное отделение. Цепочка на плечо (металл)",
        "pictures": ["../img/products/bag-clutch/Group 331.png", "../img/products/bag-clutch/Group 334.png", "../img/products/bag-clutch/Group 335.png", "../img/products/bag-clutch/Rectangle 169.png", "../img/products/bag-clutch/Rectangle 169-1.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "clutch1",
        "category": "bags",
        "flag": "Новинка",
        "sale": false,
        "name": "Клатч №1",
        "oldprice": 2290,
        "newprice": 1690,
        "img": "../img/products/clutch1/productCard.jpg",
        "size": "25*17",
        "description": "Два основных большых отделения, три кармана, два их них на молнии. Регулируемый ремень на плечо. Три вида рисунка.",
        "pictures": ["../img/products/clutch1/Group 331.png", "../img/products/clutch1/Group 337.png", "../img/products/clutch1/Group 338.png", "../img/products/clutch1/Rectangle 169.png", "../img/products/clutch1/Rectangle 169-1.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "clutch2",
        "category": "bags",
        "flag": "Новинка",
        "sale": false,
        "name": "Клатч №2",
        "oldprice": 2290,
        "newprice": 1690,
        "img": "../img/products/clutch2/productCard.png",
        "size": "25*17",
        "description": "Два основных большых отделения, три кармана, два их них на молнии. Регулируемый ремень на плечо. Три вида рисунка.",
        "pictures": ["../img/products/clutch2/Group 331.png","../img/products/clutch2/Frame 1.png", "../img/products/clutch2/Group 337.png", "../img/products/clutch2/Group 339.png", "../img/products/clutch2/Rectangle 169-1.png", "../img/products/clutch2/Rectangle 169-2.png", "../img/products/clutch2/Rectangle 169-3.png", "../img/products/clutch2/Rectangle 170.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "clutch3",
        "category": "bags",
        "flag": "Новинка",
        "sale": false,
        "name": "Клатч №3",
        "oldprice": 2290,
        "newprice": 1690,
        "img": "../img/products/clutch3/productCard.png",
        "size": "25*17",
        "description": "Два основных большых отделения, три кармана, два их них на молнии. Регулируемый ремень на плечо. Три вида рисунка.",
        "pictures": ["../img/products/clutch3/Group 331.png", "../img/products/clutch3/Group 337.png", "../img/products/clutch3/Group 339.png", "../img/products/clutch3/Rectangle 169.png", "../img/products/clutch3/Rectangle 169-1.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "rainbow-clutch",
        "category": "bags",
        "flag": "Новинка",
        "sale": false,
        "name": "Радужная сумочка-клатч",
        "oldprice": 2200,
        "newprice": 1390,
        "img": "../img/products/rainbow-clutch/productCard.png",
        "size": "28*18*7",
        "description": "Одно основное отделение, три кармана один из них под молнией. Цепочка на плечо (металл)",
        "pictures": ["../img/products/rainbow-clutch/Rectangle 169.png", "../img/products/rainbow-clutch/Rectangle 169-1.png", "../img/products/rainbow-clutch/Frame 1.png", "../img/products/rainbow-clutch/Rectangle 171.png", "../img/products/rainbow-clutch/Rectangle 172.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "purse2",
        "category": "purse",
        "flag": "",
        "sale": false,
        "name": "Кошлёк №2",
        "oldprice": 1200,
        "newprice": 690,
        "img": "../img/products/purse2/productCard.png",
        "size": "20x10x2.5",
        "description": "Три основных отделения, множество отделений под карточки-визитки, карман под молнией для мелочи.",
        "pictures": ["../img/products/purse2/Group 335.png", "../img/products/purse2/Group 337.png", "../img/products/purse2/Group 338.png", "../img/products/purse2/Rectangle 169.png", "../img/products/purse2/Rectangle 169-1.png", "../img/products/purse2/Rectangle 169-2.png", "../img/products/purse2/Rectangle 169-3.png"],
        "material": "Полиуретан/Нейлон",
    },
    {
        "id": "purse3",
        "category": "purse",
        "flag": "",
        "sale": false,
        "name": "Кошлёк №3",
        "oldprice": 1200,
        "newprice": 690,
        "img": "../img/products/purse3/productCard.png",
        "size": "20x10x2.5",
        "description": "Три основных отделения, множество отделений под карточки-визитки, карман под молнией для мелочи.",
        "pictures": ["../img/products/purse3/Group 335.png", "../img/products/purse3/Group 337.png", "../img/products/purse3/Rectangle 169.png", "../img/products/purse3/Rectangle 169-1.png", "../img/products/purse3/Rectangle 169-2.png", "../img/products/purse3/Rectangle 169-3.png"],
        "material": "Полиуретан/Нейлон",
    }
]

